name: financer-dev

services:
  mysql:
    image: mysql:9
    container_name: financer-dev-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: financer
      MYSQL_USER: financer
      MYSQL_PASSWORD: financer
    volumes:
      - ./.data/database:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: financer-dev-redis
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
